const songs = [
  {
    index: 1,
    id: "afghan-jalebi",
    name: "Afghan Jalebi",
    album: "Phantom",
    length: "03:44",
    artists: "Pritam, Akhtar Chanal Zahri",
    song: "/songs/afghan-jalebi.mp3",
    link: "/songs/afghan-jalebi",
    cover: "/songcovers/afghan-jalebi.jpg",
  },
  {
    index: 2,
    id: "ambarsariya",
    name: "Ambarsariya",
    album: "Fukrey",
    length: "04:08",
    artists: "Sona Mohapatra, Ram Sampath",
    song: "/songs/ambarsariya.mp3",
    link: "/songs/ambarsariya",
    cover: "/songcovers/ambarsariya.jfif",
  },
  {
    index: 3,
    id: "badtameez-dil",
    name: "Badtameez Dil",
    album: "Ye Jawani Hai Deewani",
    length: "04:12",
    artists: "Pritam, Benny Dayal",
    song: "/songs/badtameez-dil.mp3",
    link: "/songs/badtameez-dil",
    cover: "/songcovers/badtameez-dil.jfif",
  },
  {
    index: 4,
    id: "bones",
    name: "Bones",
    album: "Mercury - Acts 1 & 2",
    length: "02:45",
    artists: "Imagine Dragons",
    song: "/songs/bones.mp3",
    link: "/songs/bones",
    cover: "/songcovers/bones.jfif",
  },
  {
    index: 5,
    id: "boyfriend",
    name: "Boyfriend",
    album: "P-Pop Culture",
    length: "02:41",
    artists: "Karan Aujla, Ikky",
    song: "/songs/boyfriend.mp3",
    link: "/songs/boyfriend",
    cover: "/songcovers/boyfriend.jfif",
  },
  {
    index: 6,
    id: "chaar-kadam",
    name: "Chaar Kadam",
    album: "PK",
    length: "04:02",
    artists: "Shaan, Shreya Ghoshal, Shantanu Moitra",
    song: "/songs/chaar-kadam.mp3",
    link: "/songs/chaar-kadam",
    cover: "/songcovers/chaar-kadam.jfif",
  },
  {
    index: 7,
    id: "chammak-challo",
    name: "Chammak Challo",
    album: "Ra-One",
    length: "04:05",
    artists: "Vishal-Shekhar, Akon",
    song: "/songs/chammak-challo.mp3",
    link: "/songs/chammak-challo",
    cover: "/songcovers/chammak-challo.webp",
  },
  {
    index: 8,
    id: "character-dheela",
    name: "Character Dheela",
    album: "Ready",
    length: "03:47",
    artists: "Pritam, Neeraj Shridhar, Amrita Kak",
    song: "/songs/character-dheela.mp3",
    link: "/songs/character-dheela",
    cover: "/songcovers/character-dheela.jfif",
  },
  {
    index: 9,
    id: "cheques",
    name: "Cheques",
    album: "Still Rollin",
    length: "03:03",
    artists: "Shubh",
    song: "/songs/cheques.mp3",
    link: "/songs/cheques",
    cover: "/songcovers/cheques.jpg",
  },
  {
    index: 10,
    id: "clandestina",
    name: "Clandestina - JVSTIN Remix",
    album: "Clandestina",
    length: "02:26",
    artists: "FILV, Emma Peters",
    song: "/songs/clandestina.mp3",
    link: "/songs/clandestina",
    cover: "/songcovers/clandestina.jfif",
  },
  {
    index: 11,
    id: "deewana-deewana",
    name: "Deewana Deewana",
    album: "Tere Ishk Mein",
    length: "05:32",
    artists: "A.R. Rahman, Irshad Kamil",
    song: "/songs/deewana-deewana.mp3",
    link: "/songs/deewana-deewana",
    cover: "/songcovers/deewana-deewana.webp",
  },
  {
    index: 12,
    id: "dekhte-dekhte",
    name: "Dekhte Dekhte",
    album: "Batti Gul Meter Chalu",
    length: "04:16",
    artists: "Atif Aslam",
    song: "/songs/dekhte-dekhte.mp3",
    link: "/songs/dekhte-dekhte",
    cover: "/songcovers/dekhte-dekhte.webp",
  },
  {
    index: 13,
    id: "dhurandhar-title-track",
    name: "Dhurandhar - Title Track",
    album: "Dhurandhar",
    length: "02:35",
    artists: "Shashwat Sachdev, Hanumankind, Jasmine Sandlas",
    song: "/songs/dhurandhar-title-track.mp3",
    link: "/songs/dhurandhar-title-track",
    cover: "/songcovers/dhurandhar-title-track.jpg",
  },
  {
    index: 14,
    id: "ekaki-title-track",
    name: "Ekaki - Title Track",
    album: "Ekaki",
    length: "03:19",
    artists: "Ashish Chanchlani, Rio N Raz, Faizan Hussain",
    song: "/songs/ekaki-title-track.mp3",
    link: "/songs/ekaki-title-track",
    cover: "/songcovers/ekaki-title-track.jfif",
  },
  {
    index: 15,
    id: "enemy",
    name: "Enemy",
    album: "Enemy (with JID)",
    length: "03:33",
    artists: "Imagine Dragons, JID",
    song: "/songs/enemy.mp3",
    link: "/songs/enemy",
    cover: "/songcovers/enemy.jfif",
  },
  {
    index: 16,
    id: "excuses",
    name: "Excuses",
    album: "Excuses",
    length: "02:56",
    artists: "A.P. Dhillon, Gurinder Gill, Intense",
    song: "/songs/excuses.mp3",
    link: "/songs/excuses",
    cover: "/songcovers/excuses.jfif",
  },
  {
    index: 17,
    id: "fairytale",
    name: "Fairytale",
    album: "Fairytale",
    length: "02:42",
    artists: "Alexander Rybak",
    song: "/songs/fairytale.mp3",
    link: "/songs/fairytale",
    cover: "/songcovers/fairytale.jfif",
  },
  {
    index: 18,
    id: "gal-sun",
    name: "Gal Sun",
    album: "Gal Sun",
    length: "02:58",
    artists: "Sabat Batin, Rackstar",
    song: "/songs/gal-sun.mp3",
    link: "/songs/gal-sun",
    cover: "/songcovers/gal-sun.jfif",
  },
  {
    index: 19,
    id: "gangsta-s-paradise",
    name: "Gangsta's Paradise",
    album: "Gangsta's Paradise",
    length: "04:14",
    artists: "Coolio, L.V.",
    song: "/songs/gangsta-s-paradise.mp3",
    link: "/songs/gangsta-s-paradise",
    cover: "/songcovers/gangsta-s-paradise.jfif",
  },
  {
    index: 20,
    id: "happy-nation",
    name: "Happy Nation",
    album: "The Sign",
    length: "03:31",
    artists: "Ace of Base",
    song: "/songs/happy-nation.mp3",
    link: "/songs/happy-nation",
    cover: "/songcovers/happy-nation.jfif",
  },
  {
    index: 21,
    id: "haseen",
    name: "Haseen",
    album: "Haseen",
    length: "02:54",
    artists: "Talwiinder, NDS, Rippy Grewal",
    song: "/songs/haseen.mp3",
    link: "/songs/haseen",
    cover: "/songcovers/haseen.webp",
  },
  {
    index: 22,
    id: "hawa-hawa",
    name: "Hawa Hawa",
    album: "Hawa Hawa & Other Hits",
    length: "04:58",
    artists: "Hassan Jahangir",
    song: "/songs/hawa-hawa.mp3",
    link: "/songs/hawa-hawa",
    cover: "/songcovers/hawa-hawa.webp",
  },
  {
    index: 23,
    id: "ishq-jalakar",
    name: "Ishq Jalakar - Karvaan",
    album: "Dhurandhar",
    length: "04:10",
    artists: "Shashwat Sachdev, Subhadeep Das Chowdhury",
    song: "/songs/ishq-jalakar.mp3",
    link: "/songs/ishq-jalakar",
    cover: "/songcovers/ishq-jalakar.jfif",
  },
  {
    index: 24,
    id: "itna-na-mujhse-tu-pyaar-badha",
    name: "Itna Na Mujhse Tu Pyaar Badha",
    album: "Chhaya",
    length: "03:44",
    artists: "Talat Mahmood, Lata Mangeshkar",
    song: "/songs/itna-na-mujhse-tu-pyaar-badha.mp3",
    link: "/songs/itna-na-mujhse-tu-pyaar-badha",
    cover: "/songcovers/itna-na-mujhse-tu-pyaar-badha.jfif",
  },
  {
    index: 25,
    id: "jaan-se-guzarte-hai",
    name: "Jaan Se Guzarte Hai",
    album: "Dhurandhar The Revenge",
    length: "05:32",
    artists: "Shashwat Sachdev, Khan Saab, UNFAK",
    song: "/songs/jaan-se-guzarte-hai.mp3",
    link: "/songs/jaan-se-guzarte-hai",
    cover: "/songcovers/jaan-se-guzarte-hai.jfif",
  },
  {
    index: 26,
    id: "jhol",
    name: "Jhol",
    album: "Jhol",
    length: "04:25",
    artists: "Maanu, Annural Khalid",
    song: "/songs/jhol.mp3",
    link: "/songs/jhol",
    cover: "/songcovers/jhol.jfif",
  },
  {
    index: 27,
    id: "likhe-jo-khat-tujhe",
    name: "Likhe Jo Khat Tujhe",
    album: "Rafi Saab - Bouncers",
    length: "04:33",
    artists: "Mohd. Rafi",
    song: "/songs/likhe-jo-khat-tujhe.mp3",
    link: "/songs/likhe-jo-khat-tujhe",
    cover: "/songcovers/likhe-jo-khat-tujhe.jfif",
  },
  {
    index: 28,
    id: "love-story",
    name: "Love Story",
    album: "Mini World",
    length: "04:44",
    artists: "Indila",
    song: "/songs/love-story.mp3",
    link: "/songs/love-story",
    cover: "/songcovers/love-story.jfif",
  },
  {
    index: 29,
    id: "lutt-le-gaya",
    name: "Lutt Le Gaya",
    album: "Dhurandhar",
    length: "04:13",
    artists: "Shashwat Sachdev, Simran Chaudhary",
    song: "/songs/lutt-le-gaya.mp3",
    link: "/songs/lutt-le-gaya",
    cover: "/songcovers/lutt-le-gaya.jfif",
  },
  {
    index: 30,
    id: "make-some-noise-for-the-desi-boyz",
    name: "Make Some Noise for the Desi Boyz",
    album: "Desi Boyz",
    length: "04:04",
    artists: "Pritam, K.K. Bob",
    song: "/songs/make-some-noise-for-the-desi-boyz.mp3",
    link: "/songs/make-some-noise-for-the-desi-boyz",
    cover: "/songcovers/make-some-noise-for-the-desi-boyz.jfif",
  },
  {
    index: 31,
    id: "mann-mera",
    name: "Mann Mera (Original Version)",
    album: "Mann Mera (Original Version)",
    length: "03:54",
    artists: "Gajendra Verma",
    song: "/songs/mann-mera.mp3",
    link: "/songs/mann-mera",
    cover: "/songcovers/mann-mera.jpg",
  },
  {
    index: 32,
    id: "mere-mehboob-qayamat-hogi",
    name: "Mere Mehboob Qayamat Hogi",
    album: "Mr. X In Bombay",
    length: "03:48",
    artists: "Kishore Kumar",
    song: "/songs/mere-mehboob-qayamat-hogi.mp3",
    link: "/songs/mere-mehboob-qayamat-hogi",
    cover: "/songcovers/mere-mehboob-qayamat-hogi.jfif",
  },
  {
    index: 33,
    id: "naal-nachna",
    name: "Naal Nachna",
    album: "Dhurandhar",
    length: "02:35",
    artists: "Shashwat Sachdev, Reble, Irshad Kamil, Afsana Khan",
    song: "/songs/naal-nachna.mp3",
    link: "/songs/naal-nachna",
    cover: "/songcovers/naal-nachna.jfif",
  },
  {
    index: 34,
    id: "naam-chale",
    name: "Naam Chale",
    album: "Naam Chale",
    length: "02:29",
    artists: "Vikram Sarkar",
    song: "/songs/naam-chale.mp3",
    link: "/songs/naam-chale",
    cover: "/songcovers/naam-chale.jfif",
  },
  {
    index: 35,
    id: "one-love",
    name: "One Love",
    album: "One Love",
    length: "02:39",
    artists: "Shubh",
    song: "/songs/one-love.mp3",
    link: "/songs/one-love",
    cover: "/songcovers/one-love.jpg",
  },
  {
    index: 36,
    id: "pal-pal-dil-ke-paas",
    name: "Pal Pal Dil Ke Paas",
    album: "Blackmail",
    length: "05:26",
    artists: "Kishore Kumar",
    song: "/songs/pal-pal-dil-ke-paas.mp3",
    link: "/songs/pal-pal-dil-ke-paas",
    cover: "/songcovers/pal-pal-dil-ke-paas.jfif",
  },
  {
    index: 37,
    id: "pasoori",
    name: "Pasoori",
    album: "Pasoori",
    length: "03:44",
    artists: "Ali Sethi, Shae Gill",
    song: "/songs/pasoori.mp3",
    link: "/songs/pasoori",
    cover: "/songcovers/pasoori.jfif",
  },
  {
    index: 38,
    id: "pungi",
    name: "Pungi",
    album: "Agent Vinod",
    length: "04:10",
    artists: "Pritam, Mika Singh, Nakash Aziz, Javed Jaffrey",
    song: "/songs/pungi.mp3",
    link: "/songs/pungi",
    cover: "/songcovers/pungi.webp",
  },
  {
    index: 39,
    id: "royalty",
    name: "Royalty",
    album: "Not Specified",
    length: "03:43",
    artists: "Egzod, Maestro Chives",
    song: "/songs/royalty.mp3",
    link: "/songs/royalty",
    cover: "/songcovers/royalty.jfif",
  },
  {
    index: 40,
    id: "rum-rum-rum",
    name: "Rum Rum Rum",
    album: "Ekaki",
    length: "02:51",
    artists: "Nakash Aziz, Bosco Martis, Ashish Chanchlani, Sreejith Narayanan",
    song: "/songs/rum-rum-rum.mp3",
    link: "/songs/rum-rum-rum",
    cover: "/songcovers/rum-rum-rum.jpg",
  },
  {
    index: 41,
    id: "saanson-ki-mala-remix",
    name: "Saanson Ki Mala - Remix",
    album: "Saanson Ki Mala",
    length: "04:42",
    artists: "UNFAK",
    song: "/songs/saanson-ki-mala-remix.mp3",
    link: "/songs/saanson-ki-mala-remix",
    cover: "/songcovers/saanson-ki-mala-remix.jfif",
  },
  {
    index: 42,
    id: "sahiba",
    name: "Sahiba",
    album: "Sahiba",
    length: "03:03",
    artists: "Aditya Rikhari",
    song: "/songs/sahiba.mp3",
    link: "/songs/sahiba",
    cover: "/songcovers/sahiba.jpg",
  },
  {
    index: 43,
    id: "saiyaara",
    name: "Saiyaara",
    album: "Saiyaara",
    length: "06:10",
    artists: "Tanishk Bagchi, Faheem Abdullah, Irhsad Kamil",
    song: "/songs/saiyaara.mp3",
    link: "/songs/saiyaara",
    cover: "/songcovers/saiyaara.jfif",
  },
  {
    index: 44,
    id: "shararat",
    name: "Shararat",
    album: "Dhurandhar",
    length: "03:44",
    artists: "Shashwat Sachdev, Jasmine Sandlas, Madhubanti Bagchi",
    song: "/songs/shararat.mp3",
    link: "/songs/shararat",
    cover: "/songcovers/shararat.jfif",
  },
  {
    index: 45,
    id: "skyfall",
    name: "Skyfall",
    album: "007",
    length: "04:49",
    artists: "Adele",
    song: "/songs/skyfall.mp3",
    link: "/songs/skyfall",
    cover: "/songcovers/skyfall.jfif",
  },
  {
    index: 46,
    id: "tere-liye",
    name: "Tere Liye",
    album: "Prince",
    length: "04:36",
    artists: "Pritam, Atif Aslam, Shreya Ghoshal",
    song: "/songs/tere-liye.mp3",
    link: "/songs/tere-liye",
    cover: "/songcovers/tere-liye.jfif",
  },
  {
    index: 47,
    id: "tous-les-memes",
    name: "Tous les mêmes",
    album: "Racine Carrée",
    length: "03:37",
    artists: "Stormae",
    song: "/songs/tous-les-memes.mp3",
    link: "/songs/tous-les-memes",
    cover: "/songcovers/tous-les-memes.jfif",
  },
  {
    index: 48,
    id: "toxic",
    name: "Toxic",
    album: "Serotonin Dreams",
    length: "02:50",
    artists: "BoyWithUke",
    song: "/songs/toxic.mp3",
    link: "/songs/toxic",
    cover: "/songcovers/toxic.jfif",
  },
  {
    index: 49,
    id: "tum-to-thehre-pardesi",
    name: "Tum To Thehre Pardesi",
    album: "Tum To Thehre Pardesi",
    length: "14:34",
    artists: "Altaf Raja",
    song: "/songs/tum-to-thehre-pardesi.mp3",
    link: "/songs/tum-to-thehre-pardesi",
    cover: "/songcovers/tum-to-thehre-pardesi.jfif",
  },
  {
    index: 50,
    id: "udaarian",
    name: "Udaarian",
    album: "Seasons of Sartaaj",
    length: "05:50",
    artists: "Satinder Sartaaj",
    song: "/songs/udaarian.mp3",
    link: "/songs/udaarian",
    cover: "/songcovers/udaarian.jfif",
  },
];

export default songs;
